import type { ItemIllustrationKind } from "@/components/site/item-illustration";

export type WorkspaceLocale = "de" | "en";
export const workspaceText = {
  de: {
    overview: "Übersicht", items: "Gegenstände", reservations: "Reservierungen", members: "Mitglieder", settings: "Einstellungen",
    home: "Euer gemeinsamer Platz", privateGroup: "Nur für eure Gruppe", navigation: "Hauptnavigation", skip: "Zum Inhalt", help: "Hilfe & Kontakt",
    greeting: "Hallo", overviewHint: "Alles im Blick. Gemeinsam nutzen, einfach organisieren.", nextSteps: "Nächste Schritte", nextStepsHint: "Was möchtest du als Nächstes erledigen?",
    pending: "Offene Anfragen", borrowed: "Ausgeliehen", dueSoon: "Bald fällig", overdue: "Überfällig", upcoming: "Die nächsten Ausleihen", viewAll: "Alle ansehen",
    addItem: "Gegenstand hinzufügen", addItemHint: "Trage ein, was ihr miteinander teilen möchtet.", reserve: "Reservieren", reserveHint: "Wähle einen Gegenstand und deinen Zeitraum.", invite: "Mitglied einladen", inviteHint: "Holt eure Gruppe an einen gemeinsamen Ort.",
    welcome: "Willkommen bei LeihNest", createGroup: "Gruppe erstellen", firstGroup: "Ein Nest für eure Gemeinschaft", firstGroupHint: "Ob Verein, Freundeskreis oder Hausgemeinschaft: Hier bekommen eure gemeinsamen Dinge einen festen Platz.", groupName: "Gruppenname", groupExample: "Zum Beispiel Gartenfreunde Nord", groupNameHint: "Der Name ist nur für eure Mitglieder sichtbar.", invitedHint: "Du wurdest eingeladen? Öffne den persönlichen Einladungslink, den deine Gruppe dir geschickt hat.", noGroup: "Zuerst braucht ihr eine Gruppe", noGroupHint: "Erstelle eure Gruppe oder nimm eine Einladung an. Danach findest du hier eure gemeinsamen Gegenstände.",
    stepInventory: "Gegenstände sammeln", stepInventoryHint: "Name, Menge und Lagerort genügen für den Anfang.", stepMembers: "Gemeinsam starten", stepMembersHint: "Lade die Menschen ein, mit denen du teilen möchtest.", stepBorrow: "Ausleihen organisieren", stepBorrowHint: "Von der ersten Anfrage bis zur bestätigten Rückgabe.",
    inventoryHint: "Entdecke, was ihr gemeinsam habt, und plane deine nächste Ausleihe.", searchItems: "Gegenstände durchsuchen", searchHint: "Name, Beschreibung oder Lagerort", search: "Suchen", reset: "Zurücksetzen", total: "im Bestand", handedOut: "ausgegeben", location: "Lagerort", noLocation: "Lagerort noch nicht angegeben", description: "Beschreibung", name: "Name", quantity: "Anzahl", details: "Details", edit: "Bearbeiten", save: "Speichern", cancel: "Abbrechen", archive: "Archivieren", archiveConfirm: "Diesen Gegenstand archivieren? Bestehende Reservierungen bleiben erhalten.", itemNameExample: "Zum Beispiel Pavillon 3 × 3 m", locationExample: "Zum Beispiel Vereinsheim, Regal 2", descriptionHint: "Was sollten andere vor der Ausleihe wissen?", emptyItems: "Hier entsteht euer gemeinsamer Bestand", emptyItemsHint: "Füge den ersten Gegenstand hinzu. Eure Mitglieder können ihn anschließend reservieren.", memberEmptyItems: "Eure Gruppe hat noch keine Gegenstände erfasst. Bitte eine verantwortliche Person, den Bestand anzulegen.", noResults: "Keine passenden Gegenstände", noResultsHint: "Probiere einen anderen Suchbegriff oder setze die Suche zurück.", archiveHint: "Archivierte Gegenstände verschwinden aus dem Bestand, nicht aus eurem Verlauf.",
    reservationsHint: "Anfragen, Abholungen und Rückgaben an einem Ort.", newReservation: "Neue Reservierung", requestReservation: "Reservierung anfragen", chooseItem: "Gegenstand wählen", collection: "Abholung", returnDate: "Rückgabe", purpose: "Anlass oder Hinweis", optional: "optional", periodHint: "Die Zeiten gelten in deiner aktuellen Browser-Zeitzone. Die Gruppe prüft deine Anfrage vor der Freigabe.", active: "Aktuell", mine: "Meine Ausleihen", history: "Verlauf", all: "Alle", requestedBy: "Angefragt von", approve: "Freigeben", reject: "Ablehnen", confirmHandover: "Ausgabe bestätigen", confirmReturn: "Rückgabe bestätigen", returnNote: "Rückgabehinweis", returnNoteHint: "Zum Beispiel vollständig und ohne Schäden", cancelReservation: "Stornieren", cancelConfirm: "Diese Reservierung wirklich stornieren?", emptyReservations: "Noch keine Reservierungen in dieser Ansicht", emptyReservationsHint: "Neue Ausleihen erscheinen hier. Im Verlauf bleiben abgeschlossene Reservierungen erhalten.", noUpcoming: "Aktuell steht keine Ausleihe an", noUpcomingHint: "Sobald jemand einen Gegenstand anfragt, siehst du ihn hier.", previous: "Zurück", next: "Weiter", page: "Seite", of: "von", completedHint: "Diese Ausleihe ist abgeschlossen. Der Eintrag bleibt im Verlauf erhalten.", overdueHint: "Die vereinbarte Rückgabe ist bereits fällig.",
    membersHint: "Die Menschen, mit denen ihr Gegenstände teilt.", email: "E-Mail-Adresse", role: "Rolle", you: "Du", invitationInfo: "Einladungen sind sieben Tage gültig und an die angegebene E-Mail-Adresse gebunden.", createInvite: "Einladungslink erstellen", inviteCreated: "Deine Einladung ist bereit", inviteShare: "Kopiere den vollständigen Link und sende ihn an die eingeladene Person. Es wird nicht automatisch eine E-Mail versendet.", copyLink: "Link kopieren", copied: "Link kopiert", copyFailed: "Bitte markiere und kopiere den Link im Feld.", pendingInvites: "Offene Einladungen", expires: "Gültig bis", joined: "Einladung angenommen. Du bist jetzt Mitglied der Gruppe.", rolesHint: "Mitglieder können reservieren. Die Verwaltung pflegt den Bestand und bestätigt Ausleihen.",
    profile: "Dein Profil", profileHint: "So erkennen dich die anderen Mitglieder deiner Gruppe.", displayName: "Dein Name", saveProfile: "Profil speichern", groupSettings: "Eure Gruppe", saveGroup: "Gruppenname speichern", groupReadOnly: "Nur die verantwortliche Person kann den Gruppennamen ändern.", language: "Sprache", languageHint: "Diese Einstellung gilt für diesen Browser und bleibt beim nächsten Besuch erhalten.", saveLanguage: "Sprache speichern", settingsHint: "Dein Konto und eure gemeinsame Gruppe.", saved: "Deine Änderungen wurden gespeichert.", saving: "Wird gespeichert…", working: "Wird verarbeitet…", signOut: "Abmelden", signingOut: "Wird abgemeldet…", error: "Das hat leider nicht geklappt. Bitte versuche es erneut.", secureArea: "Euer privater Gruppenbereich", supportHint: "Eine Frage zu LeihNest? Schreib uns.",
    statuses: { PENDING: "Angefragt", APPROVED: "Freigegeben", HANDED_OUT: "Ausgeliehen", RETURNED: "Zurückgegeben", REJECTED: "Abgelehnt", CANCELLED: "Storniert" },
    roles: { OWNER: "Verantwortlich", ADMIN: "Verwaltung", MEMBER: "Mitglied" },
  },
  en: {
    overview: "Overview", items: "Items", reservations: "Reservations", members: "Members", settings: "Settings",
    home: "Your shared space", privateGroup: "Just for your group", navigation: "Main navigation", skip: "Skip to content", help: "Help & contact",
    greeting: "Hello", overviewHint: "Everything in one place. Share more, organise less.", nextSteps: "Next steps", nextStepsHint: "What would you like to do next?",
    pending: "Open requests", borrowed: "On loan", dueSoon: "Due soon", overdue: "Overdue", upcoming: "Upcoming loans", viewAll: "View all",
    addItem: "Add an item", addItemHint: "Add something you would like to share.", reserve: "Reserve", reserveHint: "Choose an item and the dates you need it.", invite: "Invite a member", inviteHint: "Bring your group together in one place.",
    welcome: "Welcome to LeihNest", createGroup: "Create group", firstGroup: "A home for your community", firstGroupHint: "A club, friends or neighbours: give the things you share a place of their own.", groupName: "Group name", groupExample: "For example Northside Garden Club", groupNameHint: "Only members of your group can see this name.", invitedHint: "Already invited? Open the personal invitation link your group sent you.", noGroup: "First, you need a group", noGroupHint: "Create your group or accept an invitation. Your shared items will appear here.",
    stepInventory: "Gather your items", stepInventoryHint: "Start with a name, quantity and storage location.", stepMembers: "Start together", stepMembersHint: "Invite the people you want to share with.", stepBorrow: "Organise your loans", stepBorrowHint: "From the first request to the confirmed return.",
    inventoryHint: "Discover what your group owns and plan your next loan.", searchItems: "Search items", searchHint: "Name, description or storage location", search: "Search", reset: "Reset", total: "in stock", handedOut: "on loan", location: "Storage location", noLocation: "No storage location specified", description: "Description", name: "Name", quantity: "Quantity", details: "Details", edit: "Edit", save: "Save", cancel: "Cancel", archive: "Archive", archiveConfirm: "Archive this item? Existing reservations will be kept.", itemNameExample: "For example 3 × 3 m gazebo", locationExample: "For example clubhouse, shelf 2", descriptionHint: "What should people know before borrowing this item?", emptyItems: "Your shared collection starts here", emptyItemsHint: "Add your first item so that members can start making reservations.", memberEmptyItems: "Your group has not added any items yet. Ask a group manager to add the first one.", noResults: "No matching items", noResultsHint: "Try a different search or reset your search.", archiveHint: "Archived items leave your collection, not your history.",
    reservationsHint: "Requests, collections and returns in one place.", newReservation: "New reservation", requestReservation: "Request reservation", chooseItem: "Choose an item", collection: "Collection", returnDate: "Return", purpose: "Purpose or note", optional: "optional", periodHint: "Times use your current browser time zone. A group manager will review your request before approval.", active: "Current", mine: "My loans", history: "History", all: "All", requestedBy: "Requested by", approve: "Approve", reject: "Decline", confirmHandover: "Confirm collection", confirmReturn: "Confirm return", returnNote: "Return note", returnNoteHint: "For example complete and undamaged", cancelReservation: "Cancel reservation", cancelConfirm: "Really cancel this reservation?", emptyReservations: "No reservations in this view yet", emptyReservationsHint: "New loans appear here. Completed reservations stay in your history.", noUpcoming: "No upcoming loans right now", noUpcomingHint: "As soon as someone requests an item, you will see it here.", previous: "Previous", next: "Next", page: "Page", of: "of", completedHint: "This loan is complete. The record stays in your history.", overdueHint: "The agreed return time has passed.",
    membersHint: "The people you share your collection with.", email: "Email address", role: "Role", you: "You", invitationInfo: "Invitations are valid for seven days and are linked to the specified email address.", createInvite: "Create invitation link", inviteCreated: "Your invitation is ready", inviteShare: "Copy the full link and send it to the person you invited. No email is sent automatically.", copyLink: "Copy link", copied: "Link copied", copyFailed: "Please select and copy the link in the field.", pendingInvites: "Pending invitations", expires: "Valid until", joined: "Invitation accepted. You are now a member of the group.", rolesHint: "Members can request loans. Managers maintain the collection and confirm loans.",
    profile: "Your profile", profileHint: "Help the other members of your group recognise you.", displayName: "Your name", saveProfile: "Save profile", groupSettings: "Your group", saveGroup: "Save group name", groupReadOnly: "Only the group owner can change the group name.", language: "Language", languageHint: "This preference applies to this browser and will be remembered for your next visit.", saveLanguage: "Save language", settingsHint: "Your account and your shared group.", saved: "Your changes have been saved.", saving: "Saving…", working: "Working…", signOut: "Sign out", signingOut: "Signing out…", error: "Something went wrong. Please try again.", secureArea: "Your private group space", supportHint: "Have a question about LeihNest? Write to us.",
    statuses: { PENDING: "Requested", APPROVED: "Approved", HANDED_OUT: "On loan", RETURNED: "Returned", REJECTED: "Declined", CANCELLED: "Cancelled" },
    roles: { OWNER: "Owner", ADMIN: "Manager", MEMBER: "Member" },
  },
} as const;
export type WorkspaceText = typeof workspaceText[WorkspaceLocale];
export type ReservationState = keyof typeof workspaceText.de.statuses;
export type MemberRole = keyof typeof workspaceText.de.roles;

export function resolveWorkspaceLocale(preference?: string, acceptLanguage?: string): WorkspaceLocale {
  if (preference === "de" || preference === "en") return preference;
  const languages = (acceptLanguage ?? "").split(",").map((entry) => {
    const [tag, weight] = entry.trim().split(";q=");
    return { language: tag.split("-")[0].toLowerCase(), weight: weight ? Number(weight) : 1 };
  }).filter(({ language, weight }) => ["de", "en"].includes(language) && weight > 0).sort((a,b) => b.weight-a.weight);
  return languages[0]?.language === "en" ? "en" : "de";
}
export function reservationFilter(value?: string): "active" | "mine" | "pending" | "borrowed" | "history" | "all" {
  return ["active", "mine", "pending", "borrowed", "history", "all"].includes(value ?? "") ? value as ReturnType<typeof reservationFilter> : "active";
}
export function pageNumber(value?: string): number {
  const parsed=Number(value);
  return Number.isSafeInteger(parsed) && parsed > 0 ? Math.min(parsed,100000) : 1;
}
export function itemKind(name: string): ItemIllustrationKind {
  if (/pavillon|pavilion|gazebo|zelt|tent/i.test(name) && !/bierzeltgarnitur/i.test(name)) return "pavilion";
  if (/garnitur|bank|bänk|bench|tisch|table/i.test(name)) return "benches";
  if (/beamer|projector/i.test(name)) return "projector";
  if (/lautsprecher|speaker|musikanlage|sound/i.test(name)) return "speaker";
  return "generic";
}
export function initials(name: string): string {
  return name.trim().split(/\s+/).slice(0,2).map(part=>part[0] ?? "").join("").toLocaleUpperCase();
}
