import Link from "next/link";
import type { ReactNode } from "react";
import { initials, workspaceText, type WorkspaceLocale } from "@/features/workspace/workspace";
import { usageSeries, inventoryLabelKey, activityTime, type DashboardLoan } from "@/features/design/dashboard-model";
import { ItemPhoto, photoForItem } from "./item-photo";
import { NestIcon, type NestIconName } from "./icons";
import { LocalTime } from "@/components/app/workspace-controls";
import { LoanCalendar } from "./loan-calendar";
import { dashboardCopy } from "./dashboard-copy";
export type DashboardItem={id:string;name:string;totalQuantity:number;location:string|null;imageId?:string|null};
export type DashboardMember={id:string;name:string};
export type DashboardViewProps={locale:WorkspaceLocale;name:string;groupName:string;manage:boolean;items:DashboardItem[];itemCount:number;loans:DashboardLoan[];members:DashboardMember[];memberCount:number;now:string};
function PanelHeading({ icon, title, href, link }: { icon:NestIconName;title:string;href?:string;link?:string }) {
  return <header className="dash-panel-heading"><h2><NestIcon name={icon}/>{title}</h2>{href && <Link href={href}>{link}<NestIcon name="arrow"/></Link>}</header>;
}
function Metric({ icon, value, label, hint, href }: {icon:NestIconName;value:number;label:string;hint?:string;href:string}){
  return <Link className="dash-metric" href={href}><span className="dash-metric-icon"><NestIcon name={icon}/></span><div><strong>{value.toLocaleString()}</strong><span>{label}</span>{hint && <small>{hint}</small>}</div></Link>;
}
function UsageChart({loans,now,locale}:{loans:DashboardLoan[];now:string;locale:WorkspaceLocale}){
  const t=dashboardCopy[locale];const series=usageSeries(loans,now);const total=series.reduce((n,b)=>n+b.count,0);const maximum=Math.max(4,...series.map(b=>b.count));const ceiling=Math.ceil(maximum/4)*4;
  return <section className="dash-panel dash-usage"><PanelHeading icon="chart" title={t.usage}/><div className="dash-chart-total"><strong>{total}</strong><span>{t.loansTotal}</span></div><div className="dash-chart" aria-hidden="true"><div className="dash-chart-axis">{[1,.75,.5,.25,0].map(v=><span key={v}>{ceiling*v}</span>)}</div><div className="dash-chart-bars">{series.map(bucket=><div key={bucket.key} className="dash-chart-column"><div className="dash-chart-bar-track"><span style={{height:`${bucket.count/ceiling*100}%`}} title={`${bucket.key}: ${bucket.count}`}/></div><small>{new Intl.DateTimeFormat(locale,{month:"short",timeZone:"UTC"}).format(new Date(bucket.date))}</small></div>)}</div></div><table className="nest-visually-hidden"><caption>{t.usage}</caption><thead><tr><th scope="col">{t.months}</th><th scope="col">{t.onLoan}</th></tr></thead><tbody>{series.map(b=><tr key={b.key}><th scope="row">{b.key}</th><td>{b.count}</td></tr>)}</tbody></table><p className="dash-chart-note">{t.chartNote}</p></section>;
}
function SmallEmpty({ children }: {children:ReactNode}) {return <p className="dash-small-empty">{children}</p>;}
export function DashboardView({locale,name,groupName,manage,items,itemCount,loans,members,memberCount,now}:DashboardViewProps){
  const t=dashboardCopy[locale];const active=loans.filter(row=>["PENDING","APPROVED","HANDED_OUT"].includes(row.status));const onLoan=loans.filter(row=>row.status==="HANDED_OUT");
  const upcoming=[...active].sort((a,b)=>a.startsAt.localeCompare(b.startsAt)).slice(0,4);
  const activity=[...loans].sort((a,b)=>activityTime(b).localeCompare(activityTime(a))).slice(0,3);
  const quick=[ [t.newReservation,"/app/reservations?new=1#new-reservation","calendar"], ...(manage?[[t.invite,"/app/members?new=1#new-invitation","people"],[t.group,"/app/settings#group-settings","settings"]]:[[t.myLoans,"/app/reservations?filter=mine","box"],[t.members,"/app/members","people"]]) ] as [string,string,NestIconName][];
  return <section className="concept-dashboard" data-concept="dashboard"><header className="dash-greeting"><h1>{t.hello} {name.split(" ")[0]}!</h1><p>{t.intro} {groupName}.</p><span className="dash-header-motto" aria-hidden="true">{t.motto}</span></header>
    <div className="dash-grid"><div className="dash-primary"><div className="dash-metrics"><Metric icon="box" value={itemCount} label={t.items} hint={t.inventory} href="/app/items"/><Metric icon="calendar" value={active.length} label={t.active} href="/app/reservations"/><Metric icon="people" value={memberCount} label={t.members} hint={t.inGroup} href="/app/members"/><Metric icon="leaf" value={onLoan.length} label={t.onLoan} hint={t.currently} href="/app/reservations?filter=borrowed"/></div>
      <section className="dash-panel dash-inventory"><PanelHeading icon="box" title={t.ourItems} href="/app/items" link={t.viewItems}/>{items.length ? <div className="dash-item-cards">{items.slice(0,5).map(item=>{
        const status=inventoryLabelKey(item.id,loans,now);
        return <article key={item.id}><div className="dash-item-image">{item.imageId?<img className="dash-real-item-photo" src={`/api/media/${item.imageId}/card`} alt=""/>:<ItemPhoto kind={photoForItem(item.name)} name={item.name} symbolic locale={locale}/>}<Link className="dash-item-open" href={`/app/items?q=${encodeURIComponent(item.name)}`} aria-label={`${t.manage}: ${item.name}`}><NestIcon name="chevron"/></Link></div><div className="dash-item-copy"><h3>{item.name}</h3><p>{item.location || t.noLocation}</p><span className={`dash-item-status ${status}`}>{t[status]}</span><div><small>{item.totalQuantity} {t.quantity}</small><Link href={`/app/reservations?item=${encodeURIComponent(item.id)}&new=1#new-reservation`} aria-label={`${t.newReservation}: ${item.name}`}><NestIcon name="calendar"/></Link></div></div></article>;
      })}</div> : <div className="dash-inventory-empty"><NestIcon name="box"/><h3>{workspaceText[locale].emptyItems}</h3><p>{manage?workspaceText[locale].emptyItemsHint:workspaceText[locale].memberEmptyItems}</p>{manage && <Link className="dash-primary-button" href="/app/items?new=1#new-item"><NestIcon name="plus"/>{t.addItem}</Link>}</div>}</section>
      <div className="dash-two-up"><section className="dash-panel dash-upcoming"><PanelHeading icon="calendar" title={t.upcoming} href="/app/reservations" link={t.viewAll}/>{upcoming.length?<div className="dash-compact-list">{upcoming.map(row=><Link href={`/app/reservations?filter=all#reservation-${encodeURIComponent(row.id)}`} key={row.id}><ItemPhoto kind={photoForItem(row.item.name)} name={row.item.name}/><div><h3>{row.item.name}</h3><p>{t.by} {row.user.name}</p></div><time dateTime={row.startsAt}>{new Intl.DateTimeFormat(locale,{day:"numeric",month:"short",timeZone:"Europe/Berlin"}).format(new Date(row.startsAt))}</time><NestIcon name="chevron"/></Link>)}</div>:<SmallEmpty>{t.noLoansHint}</SmallEmpty>}</section><UsageChart loans={loans} now={now} locale={locale}/></div>
      <div className="dash-two-up"><section className="dash-panel dash-activity"><PanelHeading icon="activity" title={t.activity} href="/app/reservations?filter=all" link={t.viewAll}/>{activity.length?<div className="dash-activity-list">{activity.map(row=><Link key={row.id} href={`/app/reservations?filter=all#reservation-${encodeURIComponent(row.id)}`}><span className="dash-avatar">{initials(row.user.name)}</span><div><p><strong>{row.user.name}</strong> · {row.item.name}</p><small>{workspaceText[locale].statuses[row.status]} · <LocalTime value={activityTime(row)} locale={locale}/></small></div><NestIcon name="chevron"/></Link>)}</div>:<SmallEmpty>{t.noActivity}</SmallEmpty>}</section><section className="dash-panel dash-members"><PanelHeading icon="people" title={t.ourMembers} href="/app/members" link={t.viewAll}/><div className="dash-member-avatars">{members.slice(0,7).map(member=><Link className="dash-avatar" key={member.id} href="/app/members" title={member.name}>{initials(member.name)}</Link>)}{memberCount>7 && <Link className="dash-avatar" href="/app/members">+{memberCount-7}</Link>}</div><strong>{memberCount} {t.memberLabel}</strong><p>{t.membersNote}</p></section></div>
      <p className="dash-photo-notice">{t.photoNotice} <Link href={`/bildnachweise${locale==="en"?"?lang=en":""}`}>{t.credits}</Link></p>
    </div><aside className="dash-secondary"><section className="dash-panel dash-quick">{manage?<Link className="dash-primary-button" href="/app/items?new=1#new-item"><NestIcon name="plus"/>{t.addItem}</Link>:<Link className="dash-primary-button" href="/app/reservations?new=1#new-reservation"><NestIcon name="plus"/>{t.newReservation}</Link>}<h2><NestIcon name="activity"/>{t.quick}<span className="nest-visually-hidden">{t.nextSteps}</span></h2><div>{quick.map(([label,href,icon])=><Link href={href} key={href}><span><NestIcon name={icon}/></span>{label}<NestIcon name="chevron"/></Link>)}</div></section><LoanCalendar loans={active} now={now} locale={locale}/><section className="dash-together"><p>{t.little}</p><small>{t.thanks}</small></section></aside></div>
  </section>;
}
